CREATE TABLE `Build` (
	`id` varchar(191) NOT NULL,
	`avatarId` int NOT NULL,
	`level` int NOT NULL,
	`ascension` int NOT NULL,
	`fetterLevel` int NOT NULL,
	`constellation` int NOT NULL,
	`skillDepotId` int NOT NULL,
	`fightProps` text NOT NULL,
	`skillLevel` text NOT NULL,
	`critValue` decimal(65,30),
	`critValueArtifactsOnly` decimal(65,30),
	`plumeId` int,
	`plumeSetId` int,
	`plumeMainStat` text,
	`plumeSubStats` text,
	`plumeSubstatsId` text,
	`plumeCritValue` decimal(65,30),
	`flowerId` int,
	`flowerSetId` int,
	`flowerMainStat` text,
	`flowerSubStats` text,
	`flowerSubstatsId` text,
	`flowerCritValue` decimal(65,30),
	`sandsId` int,
	`sandsSetId` int,
	`sandsMainStat` text,
	`sandsSubStats` text,
	`sandsSubstatsId` text,
	`sandsCritValue` decimal(65,30),
	`gobletId` int,
	`gobletSetId` int,
	`gobletMainStat` text,
	`gobletSubStats` text,
	`gobletSubstatsId` text,
	`gobletCritValue` decimal(65,30),
	`circletId` int,
	`circletSetId` int,
	`circletMainStat` text,
	`circletSubStats` text,
	`circletSubstatsId` text,
	`circletCritValue` decimal(65,30),
	`weaponId` int NOT NULL,
	`weaponLevel` int NOT NULL,
	`weaponPromoteLevel` int NOT NULL,
	`weaponRefinement` int NOT NULL,
	`weaponStat` text NOT NULL,
	`playerId` varchar(191) NOT NULL,
	CONSTRAINT `Build_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `HSRBuild` (
	`id` varchar(191) NOT NULL,
	`avatarId` int NOT NULL,
	`level` int NOT NULL,
	`promotion` int NOT NULL,
	`rank` int NOT NULL,
	`skillLevel` text NOT NULL,
	`critValue` decimal(65,30) NOT NULL,
	`critValueArtifactsOnly` decimal(65,30) NOT NULL,
	`attributes` text,
	`additions` text,
	`properties` text,
	`lightConeId` int,
	`lightConeLevel` int,
	`lightConePromotion` int,
	`lightConeRank` int,
	`headRelicId` int,
	`headRelicSetId` int,
	`headRelicLevel` int,
	`headRelicRarity` int,
	`headMainStat` text,
	`headSubStats` text,
	`headCritValue` decimal(65,30),
	`handsRelicId` int,
	`handsRelicSetId` int,
	`handsRelicLevel` int,
	`handsRelicRarity` int,
	`handsMainStat` text,
	`handsSubStats` text,
	`handsCritValue` decimal(65,30),
	`bodyRelicId` int,
	`bodyRelicSetId` int,
	`bodyRelicLevel` int,
	`bodyRelicRarity` int,
	`bodyMainStat` text,
	`bodySubStats` text,
	`bodyCritValue` decimal(65,30),
	`feetRelicId` int,
	`feetRelicSetId` int,
	`feetRelicLevel` int,
	`feetRelicRarity` int,
	`feetMainStat` text,
	`feetSubStats` text,
	`feetCritValue` decimal(65,30),
	`planarSphereRelicId` int,
	`planarSphereRelicSetId` int,
	`planarSphereRelicLevel` int,
	`planarSphereRelicRarity` int,
	`planarSphereMainStat` text,
	`planarSphereSubStats` text,
	`planarSphereCritValue` decimal(65,30),
	`linkRopeRelicId` int,
	`linkRopeRelicSetId` int,
	`linkRopeRelicLevel` int,
	`linkRopeRelicRarity` int,
	`linkRopeMainStat` text,
	`linkRopeSubStats` text,
	`linkRopeCritValue` decimal(65,30),
	`playerId` varchar(191) NOT NULL,
	CONSTRAINT `HSRBuild_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `HSRPlayer` (
	`id` varchar(191) NOT NULL,
	`uuid` text NOT NULL,
	`nickname` text NOT NULL,
	`profilePictureId` int NOT NULL,
	`profileCostumeId` int NOT NULL,
	`namecardId` int,
	`level` int NOT NULL,
	`signature` text NOT NULL,
	`worldLevel` int NOT NULL,
	`finishAchievementNum` int NOT NULL,
	`avatars` int NOT NULL,
	`lightCones` int NOT NULL,
	`passAreaProgress` int NOT NULL,
	`friends` int NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `HSRPlayer_id` PRIMARY KEY(`id`),
	CONSTRAINT `HSRPlayer_uuid_key` UNIQUE(`uuid`)
);
--> statement-breakpoint
CREATE TABLE `Player` (
	`id` varchar(191) NOT NULL,
	`uuid` text NOT NULL,
	`nickname` text NOT NULL,
	`profilePictureId` int NOT NULL,
	`profileCostumeId` int NOT NULL,
	`namecardId` int NOT NULL,
	`level` int NOT NULL,
	`signature` text,
	`worldLevel` int NOT NULL,
	`finishAchievementNum` int NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `Player_id` PRIMARY KEY(`id`),
	CONSTRAINT `Player_uuid_key` UNIQUE(`uuid`)
);
--> statement-breakpoint
CREATE INDEX `Build_playerId_idx` ON `Build` (`playerId`);--> statement-breakpoint
CREATE INDEX `HSRBuild_playerId_idx` ON `HSRBuild` (`playerId`);