export interface Commons {
  HP: string;
  "Percent HP": string;
  "Base HP": string;
  ATK: string;
  "Percent ATK": string;
  "Base ATK": string;
  DEF: string;
  "Percent DEF": string;
  "Base DEF": string;
  Impact: string;
  "Impact Reduction": string;
  "CRIT Rate": string;
  "CRIT DMG": string;
  "CRIT DMG Reduction": string;
  "CRIT RES Rate": string;
  PEN: string;
  "PEN Ratio": string;
  "Anomaly Mastery": string;
  "Anomaly Mastery Ratio": string;
  "Daze Bonus": string;
  "DMG Bonus": string;
  "Electric DMG Bonus": string;
  "Ether DMG Bonus": string;
  "Fire DMG Bonus": string;
  "Ice DMG Bonus": string;
  "Physical DMG Bonus": string;
  "Anomaly Buildup Rate": string;
  "Anomaly Proficiency": string;
  Electric: string;
  Ether: string;
  Fire: string;
  Ice: string;
  Physical: string;
  Wind: string;
  "Energy Generation Rate": string;
  "Energy Limit": string;
  "Energy Regen": string;
  "Base Energy Regen": string;
}
